default_language_version:
  python: python3.9
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: pretty-format-json
      args:
        - "--autofix"
        - "--indent=4"
        - "--no-sort-keys"
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args:
        - "--profile=black"
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      args:
        - "--max-line-length=80"
      additional_dependencies:
        - pep8-naming
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-simplify
        - flake8-docstrings
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
    - id: mypy
      additional_dependencies:
        - types-dataclasses >= 0.1.3
        - types-typed-ast >= 1.4.1
        - types-python-dateutil
        - types-PyYAML
        - pytest
